# Generated by Django 5.1.7 on 2025-03-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_image', models.URLField(default='https://endlessicons.com/wp-content/uploads/2012/11/loading-icon-614x460.png')),
            ],
        ),
    ]
